### ISSUE TITLE
Prevent cache page when http requests failed 

### ISSUE THREAD

**Issue by DanialV** [eneajaho/ngx-isr#15]
It is nice to have if there is an option for caching strategy when caching a page that contains HTTP requests and for some reason (web server is unreachable) one request failed page don't cache and user serve with old cache version in this way user never seen empty page or some loading state on page when original  server is down

**Comment by eneajaho** [comment]
Thanks for opening this issue Danial. 
I will check what I can do about it. 

A solution would be to add an http interceptor only on the server side and check if any request fails. 
And probably will add an option to ISRHandler to error when rendering pages on failed requests.
