### ISSUE TITLE
File System CacheHandler

### ISSUE THREAD

**Issue by radekdob** [eneajaho/ngx-isr#21]
Hi,
I see in the repo FIleSystemChache implementation https://github.com/eneajaho/ngx-isr/blob/main/projects/ngx-isr/src/lib/cache-handlers/filesystem-cache-handler.ts 

but it is not part of published library 0.3.0v.

1.Is it ready or planned to be published in upcoming version?
2.Or is there hybrid mode(cache+prerender) available?

Btw, great job!

**Comment by eneajaho** [comment]
Hi @radekdob 

I just published the new version. 

Here are the [release notes](https://github.com/eneajaho/ngx-isr/releases/tag/v.0.3.1).

It introduced the FileSystemCacheHandler. 

Give it a try, and let me know how it works, and what we can improve.

Thanks.
