### ISSUE TITLE
Error when I run a build

### ISSUE THREAD

**Issue by baucosta** [eneajaho/ngx-isr#25]
Hi guys, how's it going?

So, when I'm building my production site, it's showing the following error:

**./node_modules/ngx-isr/fesm2015/ngx-isr.mjs:666:37-47 - Error: export 'catchError' (imported as 'catchError') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip**

As far as I could see, I follow steps correctly. Nevertheless, this error's happening.

I appreciate your attention.

**Comment by baucosta** [comment]
I forgot to say. My Angular version is 14.2.2

**Comment by eneajaho** [comment]
Hello @baucosta 
This is an issue with the rxjs version you're using. The plugin is using   "rxjs": "~7.5.5", 
so probably you're in an older version and that's what is happening. 

Probably I should add rxjs to peerDependencies. 

Can you test with a new version of rxjs and let me know?

**Comment by baucosta** [comment]
Hi @eneajaho . Thanks for your help.

It worked, very good.  

I'd like to  thank you guys for this lib. It'll help us so much, rss. 

Best regards

**Comment by eneajaho** [comment]
Hi @baucosta 

Please, let us know for any inconvenience, or issue or things we can improve. 

Thanks.
