### ISSUE TITLE
Cache with many urls

### ISSUE THREAD

**Issue by baucosta** [eneajaho/ngx-isr#26]
Hello @eneajaho! 

Then, I've got to implement your lib in my project. It worked so good. I've implemented it in two projects. However, one of this, I'm getting a problem. Let me explain my context.
We have a site, which, many users access it by different urls. Our company has developed a site which can be hired by different customers. The layout, informations, site's configures, among others, are showed depending on the URL accessed. Example:

https://urlone.com
https://urltwo.com

That is, our customers have theirs domains. Their domains access our angular project. And, in our API, we've done a filter to identify which URL is being accessed. From this, we return the customer's site. 

Then, the problem is: the cache from your lib is working as expected. However, due to cache, sometimes, in a fast moment, it gets the cache of the last site accssed. Example:

I requested:  https://urlone.com. Ok, worked so good with cache. After it, I requested: https://urltwo.com.
In a fast moment, on the first load, it showed some images of the first site (urlone). I understand the why: the lib makes cache of the last page accssed (I've configured the data for 5 seconds). But, it was a problem for this context. Is it possible I make cache for differents URLs?

I hope I was clear. 

Anyway, I liked your lib. As I said before: I've implemented it in two projects. For the first one, which it has just one URL, it got very, but very good. Congrats for this project.

**Comment by baucosta** [comment]
When I said URL's, I meant "domain".

**Comment by eneajaho** [comment]
Hello @baucosta 
I would like to know if you use the InMemoryCacheHandler (the default one) or the FileSystemCacheHandler? 

One solution is to create two ISRHandler class instances (one for each site). Then on the route handler you check for the domain of the request, and serve from cache or revalidate cache for that domain.

Something like this: 


```ts
  const domainOneIsrHandler = new ISRHandler({
    indexHtml,
    invalidateSecretToken: 'MY_TOKEN',
    enableLogging: !environment.production
  });

  const domainTwoIsrHandler = new ISRHandler({
    indexHtml,
    invalidateSecretToken: 'MY_TOKEN',
    enableLogging: !environment.production
  });
  
  
  server.get('*',
    // Serve page if it exists in cache
    async (req, res, next) => {
        if (req.get('host')=== 'domainOne') {
            return await domainOneIsrHandler.serveFromCache(req, res, next);
        }

        if (req.get('host')=== 'domainTwo') {
            return await domainTwoIsrHandler.serveFromCache(req, res, next);
        }

       // don't forget to add a default case handler here, maybe create a default isr handler
    },
    // Server side render the page and add to cache if needed
    async (req, res, next) => {
        if (req.get('host')=== 'domainOne') {
            return await domainOneIsrHandler.render(req, res, next);
        }

        if (req.get('host')=== 'domainTwo') {
            return await domainTwoIsrHandler.render(req, res, next);
        }

       // don't forget to add a default case handler here, maybe create a default isr handler
    },
  );
```

Hope it helps!

**Comment by baucosta** [comment]
Hi @eneajaho ! Thanks for your answer.

So, I thought that your lib had a way to make it. But, that's not a problem. This idea might work as well. I'm gonna make it here. In my case, there are many customers, not just two. Anyway, I had an idea from your comment.

I appreciate your attention.

Best regards

**Comment by baucosta** [comment]
I forgot to let you know. I'm using InMemoryCacheHandler.

**Comment by eneajaho** [comment]
Your case is very specific and I don't think I'll add support for it. 

What you can also do is to to create your own cache handler class that implements CacheHanlder interface. This way the implementation on outside is the same as now. The custom cache handler will handle the urls differently based on the usecase. You can check how the InMemoryCacheHandler class handles stuff so you can easily create custom logic from it. 

Let me add an example here.

**Comment by eneajaho** [comment]
So, here's a repository that I have not tested but just added code on how I think it can work. 

repo: https://github.com/eneajaho/isr-multiple-domains

here's how the default in memory cache handler works: https://github.com/eneajaho/ngx-isr/blob/main/projects/ngx-isr/src/lib/cache-handlers/in-memory-cache-handler.ts 

implementation of CacheHandler that can handle multiple domains: https://github.com/eneajaho/isr-multiple-domains/blob/master/in-memory-multiple-domains-cache-handler.ts 

usage of that cache handler: https://github.com/eneajaho/isr-multiple-domains/blob/master/server.ts#L29 

So you can add a list of domains when you configure the cache handler and it will handle all the other parts. 
That's it, that's all you have to add/change.

**Comment by baucosta** [comment]
Very good, you've ever thought an implemention about it.

Nice @eneajaho . I'm gonna try it. 

Thanks for your attention.

**Comment by eneajaho** [comment]
Happy to help! Let me know about anything else. 

I'm closing this issue as there are 2 solutions for it in the comments, but feel free to reach out again.
