### ISSUE TITLE
upgrade to v15

### ISSUE THREAD

**Issue by eneajaho** [eneajaho/ngx-isr#30]

**Comment by manselman** [comment]
Hi,
is there any progress

**Comment by eneajaho** [comment]
Hi @manselman 
Yeah, https://github.com/eneajaho/ngx-isr/commit/3b4baa426863562e72ea7e0537e32363805e6734 

will do a release later today

**Comment by eneajaho** [comment]
https://github.com/eneajaho/ngx-isr/releases/tag/v.0.4.0
