### ISSUE TITLE
Invalidate/regenerate multiple urls with one request

### ISSUE THREAD

**Issue by eneajaho** [eneajaho/ngx-isr#5]
Add an api to invalidate (regenerate) multiple pages at once (using post request with urls in body)

**Comment by MasterJOI** [comment]
Hello, by the way, I would really like to have such an opportunity. For example, after adding a new post, I want to regenerate several pages at once (the main page and the list of posts).

**Comment by eneajaho** [comment]
@MasterJOI 

I was thinking to first refactor the implementation and convert the invalidate api call to be a POST call and in the payload we can send 1 or more urls for regeneration. 

It will be a breaking change, but a small one.

**Comment by eneajaho** [comment]
This should be fixed by this [commit](https://github.com/eneajaho/ngx-isr/commit/3f0c91afe116e94ece3e930911d0dc71ce312280)
